--------------------------------------------------------
--  File created - Saturday-October-26-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ACTOR
--------------------------------------------------------

  CREATE TABLE "FILME"."ACTOR" 
   (	"ACTOR_ID" NUMBER(5,0), 
	"NUME" VARCHAR2(20 BYTE), 
	"PRENUME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ACTOR_FILM
--------------------------------------------------------

  CREATE TABLE "FILME"."ACTOR_FILM" 
   (	"FILM_ID" NUMBER(5,0), 
	"ACTOR_ID" NUMBER(5,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FILM
--------------------------------------------------------

  CREATE TABLE "FILME"."FILM" 
   (	"FILM_ID" NUMBER(5,0), 
	"NUME_FILM" VARCHAR2(30 BYTE), 
	"GEN_ID" NUMBER(1,0), 
	"ANUL_APARITIEI" NUMBER(4,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GEN
--------------------------------------------------------

  CREATE TABLE "FILME"."GEN" 
   (	"GEN_ID" NUMBER(1,0), 
	"GENUL" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Sequence ACTOR_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FILME"."ACTOR_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence FILM_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FILME"."FILM_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Index ACTOR_FILM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FILME"."ACTOR_FILM_PK" ON "FILME"."ACTOR_FILM" ("FILM_ID", "ACTOR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ACTOR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FILME"."ACTOR_PK" ON "FILME"."ACTOR" ("ACTOR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FILM_FK_GEN_ID
--------------------------------------------------------

  CREATE INDEX "FILME"."FILM_FK_GEN_ID" ON "FILME"."FILM" ("GEN_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FILM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FILME"."FILM_PK" ON "FILME"."FILM" ("FILM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index GEN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FILME"."GEN_PK" ON "FILME"."GEN" ("GEN_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index NUME_ACTOR_INDEX
--------------------------------------------------------

  CREATE INDEX "FILME"."NUME_ACTOR_INDEX" ON "FILME"."ACTOR" ("NUME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index NUME_FILM_INDEX
--------------------------------------------------------

  CREATE INDEX "FILME"."NUME_FILM_INDEX" ON "FILME"."FILM" ("NUME_FILM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger ACTOR_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "FILME"."ACTOR_TRG" 
BEFORE INSERT ON ACTOR 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ACTOR_ID IS NULL THEN
      SELECT ACTOR_SEQ.NEXTVAL INTO :NEW.ACTOR_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "FILME"."ACTOR_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger FILM_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "FILME"."FILM_TRG" 
BEFORE INSERT ON FILM 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.FILM_ID IS NULL THEN
      SELECT FILM_SEQ.NEXTVAL INTO :NEW.FILM_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "FILME"."FILM_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table ACTOR
--------------------------------------------------------

  ALTER TABLE "FILME"."ACTOR" MODIFY ("PRENUME" NOT NULL ENABLE);
  ALTER TABLE "FILME"."ACTOR" ADD CONSTRAINT "ACTOR_PK" PRIMARY KEY ("ACTOR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FILME"."ACTOR" MODIFY ("NUME" NOT NULL ENABLE);
  ALTER TABLE "FILME"."ACTOR" MODIFY ("ACTOR_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ACTOR_FILM
--------------------------------------------------------

  ALTER TABLE "FILME"."ACTOR_FILM" ADD CONSTRAINT "ACTOR_FILM_PK" PRIMARY KEY ("FILM_ID", "ACTOR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FILM
--------------------------------------------------------

  ALTER TABLE "FILME"."FILM" MODIFY ("ANUL_APARITIEI" NOT NULL ENABLE);
  ALTER TABLE "FILME"."FILM" ADD CONSTRAINT "FILM_PK" PRIMARY KEY ("FILM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FILME"."FILM" MODIFY ("GEN_ID" NOT NULL ENABLE);
  ALTER TABLE "FILME"."FILM" MODIFY ("NUME_FILM" NOT NULL ENABLE);
  ALTER TABLE "FILME"."FILM" MODIFY ("FILM_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GEN
--------------------------------------------------------

  ALTER TABLE "FILME"."GEN" ADD CONSTRAINT "GEN_PK" PRIMARY KEY ("GEN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FILME"."GEN" MODIFY ("GEN_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ACTOR_FILM
--------------------------------------------------------

  ALTER TABLE "FILME"."ACTOR_FILM" ADD CONSTRAINT "ACTOR_FILM_FK1" FOREIGN KEY ("ACTOR_ID")
	  REFERENCES "FILME"."ACTOR" ("ACTOR_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "FILME"."ACTOR_FILM" ADD CONSTRAINT "ACTOR_FILM_FK2" FOREIGN KEY ("FILM_ID")
	  REFERENCES "FILME"."FILM" ("FILM_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FILM
--------------------------------------------------------

  ALTER TABLE "FILME"."FILM" ADD CONSTRAINT "FILM_FK1" FOREIGN KEY ("GEN_ID")
	  REFERENCES "FILME"."GEN" ("GEN_ID") ENABLE;
